### ISSUE TITLE
Admin credentials required?

### ISSUE THREAD

**Issue by sburkett** [ccovey/ldap-auth#14]
After some struggling, I finally got this package to work.... nice job, BTW :)

However, the only way I was able to get it to work was by specifying admin credentials (admin_username and admin_password) in config/adldap.php.

I'd rather not have admin credentials tied into the code.  Anyone have any ideas as to why this is the case?  If I remove the admin credentials, the login simply fails.

**Comment by sburkett** [comment]
This guy seems to have stumbled into the same or similar problem:

http://forums.laravel.io/viewtopic.php?id=11020

**Comment by sburkett** [comment]
I should add that the user/password combo I am authenticating with is the same as the one I put in the admin_username/admin_password fields in the config file.  That particular account is a domain administrator, so I can't really see this being a permission issue.  Not sure if that makes sense or not.

**Comment by ccovey** [comment]
The problem really isn't with authentication the problem is every other time the user visits the site within that session their user ID is checked to make sure it is still valid and in the case of ldap you get a fresh set of groups etc so you know permissions are always up to date. So unless you allow anonymous binding (most don't and they will actually lock out users if it is attempted) there is no way to bind to active directory and get the user info. That is why you are required to provide admin credentials, active directory needs them to get user information back.
